# Exercise 4 (NLP): Very Deep Learning

**Natural language processing (NLP)** is the ability of a computer program to understand human language as it is spoken. It involves a pipeline of steps and by the end of the exercise, we would be able to classify the sentiment of a given review as POSITIVE or NEGATIVE.


Before starting, it is important to understand the need for RNNs and the lecture from Stanford is a must to see before starting the exercise:

https://www.youtube.com/watch?v=iX5V1WpxxkY

When done, let's begin. 

In [3]:
# In this exercise, we will import libraries when needed so that we understand the need for it. 
# However, this is a bad practice and don't get used to it.
import numpy as np
import os

print(os.getcwd())

# read data from reviews and labels file.
with open('data/reviews.txt', 'r') as f:
    reviews_ = f.readlines()
with open('data/labels.txt', 'r') as f:
    labels = f.readlines()

D:\Dropbox\Dropbox\Master Theoretische Informatik\Very Deep Learning\WiSe 18_19\Git\Blatt 4


In [4]:
# One of the most important task is to visualize data before starting with any ML task. 
for i in range(5):
    print(labels[i] + "\t: " + reviews_[i][:100] + "...")

positive
	: bromwell high is a cartoon comedy . it ran at the same time as some other programs about school life...
negative
	: story of a man who has unnatural feelings for a pig . starts out with a opening scene that is a terr...
positive
	: homelessness  or houselessness as george carlin stated  has been an issue for years but never a plan...
negative
	: airport    starts as a brand new luxury    plane is loaded up with valuable paintings  such belongin...
positive
	: brilliant over  acting by lesley ann warren . best dramatic hobo lady i have ever seen  and love sce...




We can see there are a lot of punctuation marks like fullstop(.), comma(,), new line (\n) and so on and we need to remove it. 

Here is a list of all the punctuation marks that needs to be removed 
```
(!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~)
```


## Task 1: Remove all the punctuation marks from the reviews.
Many ways of doing it: Regex, Spacy, import punctuation from string.

In [5]:
# Make everything lower case to make the whole dataset even. 
reviews = ''.join(reviews_).lower()

In [6]:
import string
# complete the function below to remove punctuations and save it in no_punct_text

def text_without_punct(reviews):
    exclude = set(string.punctuation)
    # reviews = [ch for ch in reviews if ch not in exclude]
    cleanded = []
    temp_row = []
    for elem in reviews:
        if elem == '\n':
            cleanded.append(''.join(temp_row))
            temp_row = []
        else:
            if not (elem in exclude):
                temp_row.extend(elem)


    return cleanded

no_punct_text = text_without_punct(reviews)

for i in range(5):
    print(labels[i] + "\t: " + no_punct_text[i][:100] + "...")

positive
	: bromwell high is a cartoon comedy  it ran at the same time as some other programs about school life ...
negative
	: story of a man who has unnatural feelings for a pig  starts out with a opening scene that is a terri...
positive
	: homelessness  or houselessness as george carlin stated  has been an issue for years but never a plan...
negative
	: airport    starts as a brand new luxury    plane is loaded up with valuable paintings  such belongin...
positive
	: brilliant over  acting by lesley ann warren  best dramatic hobo lady i have ever seen  and love scen...


In [7]:
# split the formatted no_punct_text into words
def split_in_words(no_punct_text):
    erg = [elem.split(' ') for elem in no_punct_text]

    no_empty_words = []
    for row in erg:
        temp = []
        for elem in row:
            if elem != '':
                temp.append(elem)
        no_empty_words.append(temp)

    return no_empty_words

words = split_in_words(no_punct_text)
# print(words[:10])
print("The first ten words in the first sentence:", words[:10])

The first ten words in the first sentence: [['bromwell', 'high', 'is', 'a', 'cartoon', 'comedy', 'it', 'ran', 'at', 'the', 'same', 'time', 'as', 'some', 'other', 'programs', 'about', 'school', 'life', 'such', 'as', 'teachers', 'my', 'years', 'in', 'the', 'teaching', 'profession', 'lead', 'me', 'to', 'believe', 'that', 'bromwell', 'high', 's', 'satire', 'is', 'much', 'closer', 'to', 'reality', 'than', 'is', 'teachers', 'the', 'scramble', 'to', 'survive', 'financially', 'the', 'insightful', 'students', 'who', 'can', 'see', 'right', 'through', 'their', 'pathetic', 'teachers', 'pomp', 'the', 'pettiness', 'of', 'the', 'whole', 'situation', 'all', 'remind', 'me', 'of', 'the', 'schools', 'i', 'knew', 'and', 'their', 'students', 'when', 'i', 'saw', 'the', 'episode', 'in', 'which', 'a', 'student', 'repeatedly', 'tried', 'to', 'burn', 'down', 'the', 'school', 'i', 'immediately', 'recalled', 'at', 'high', 'a', 'classic', 'line', 'inspector', 'i', 'm', 'here', 'to', 'sack', 'one', 'of', 'your', 't

In [8]:
# once you are done print the ten words that should yield the following output
# oneD = sum(words, [])
words[:10]
# oneD[:10]

[['bromwell',
  'high',
  'is',
  'a',
  'cartoon',
  'comedy',
  'it',
  'ran',
  'at',
  'the',
  'same',
  'time',
  'as',
  'some',
  'other',
  'programs',
  'about',
  'school',
  'life',
  'such',
  'as',
  'teachers',
  'my',
  'years',
  'in',
  'the',
  'teaching',
  'profession',
  'lead',
  'me',
  'to',
  'believe',
  'that',
  'bromwell',
  'high',
  's',
  'satire',
  'is',
  'much',
  'closer',
  'to',
  'reality',
  'than',
  'is',
  'teachers',
  'the',
  'scramble',
  'to',
  'survive',
  'financially',
  'the',
  'insightful',
  'students',
  'who',
  'can',
  'see',
  'right',
  'through',
  'their',
  'pathetic',
  'teachers',
  'pomp',
  'the',
  'pettiness',
  'of',
  'the',
  'whole',
  'situation',
  'all',
  'remind',
  'me',
  'of',
  'the',
  'schools',
  'i',
  'knew',
  'and',
  'their',
  'students',
  'when',
  'i',
  'saw',
  'the',
  'episode',
  'in',
  'which',
  'a',
  'student',
  'repeatedly',
  'tried',
  'to',
  'burn',
  'down',
  'the',
  'sc

In [9]:
# print the total length of the words
len(words)
# len(oneD)

25000

In [10]:
# Total number of unique words
words_set = set()
for sentence in words:
    words_set.update(set(sentence))
    
len(words_set)
# len(set(oneD))

74072


Next step is to create a vocabulary. This way every word is mapped to an integer number.
```
Example: 1: hello, 2: I, 3: am, 4: Robo and so on...
```


In [11]:
# Lets create a vocab out of it

# feel free to use this import 
from collections import Counter

allwords = []
for sentence in words:
    allwords.extend(sentence)
print(allwords[:30])

## Let's keep a count of all the words and let's see how many words are there. 
def word_count(words):
    return Counter(words)

counts=word_count(allwords)

['bromwell', 'high', 'is', 'a', 'cartoon', 'comedy', 'it', 'ran', 'at', 'the', 'same', 'time', 'as', 'some', 'other', 'programs', 'about', 'school', 'life', 'such', 'as', 'teachers', 'my', 'years', 'in', 'the', 'teaching', 'profession', 'lead', 'me']


In [12]:
# If you did everything correct, this is what you should get as output. 
print (counts['wonderful'])

print (counts['bad'])

1658
9308


## Task 2: Word to Integer and Integer to word
The task is to map every word to an integer value and then vice-versa. 


In [13]:

# define a vocabulary for the words
def vocabulary(counts):
    dictionary = {}
    i = 1
    for key, val in counts.items():
        
        dictionary[i] = key
        i+=1
    
    return dictionary

vocab = vocabulary(counts)
print(len(vocab))
vocab[1]

74072


'colman'

In [14]:
# map each vocab word to an integer. Also, start the indexing with 1 as we will use 
# '0' for padding and we dont want to mix the two.
def vocabulary_to_integer(vocab):
    dictionary = {}
   
    for key, val in vocab.items():
        
        dictionary[val] = key
        
    
    return dictionary

vocab_to_int = vocabulary_to_integer(vocab)

In [15]:
# verify if the length is same and if 'and' is mapped to the correct integer value.
print(len(vocab_to_int))
vocab_to_int['bromwell'] # 'and' is not found any more since removed by stopword filter

74072


10001

Let's see what positve words in positive reviews we have and what we have in negative reviews. 

In [16]:
positive_counts = Counter()
negative_counts = Counter()

In [17]:
for i in range(len(reviews_)):
    if(labels[i] == 'positive\n'):
        for word in reviews_[i].split(" "):
            positive_counts[word] += 1
    else:
        for word in reviews_[i].split(" "):
            negative_counts[word] += 1

In [18]:
labels

['positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive\n',
 'negative\n',
 'positive

In [19]:
positive_counts.most_common()

[('', 537968),
 ('the', 173324),
 ('.', 159654),
 ('and', 89722),
 ('a', 83688),
 ('of', 76855),
 ('to', 66746),
 ('is', 57245),
 ('in', 50215),
 ('br', 49235),
 ('it', 48025),
 ('i', 40743),
 ('that', 35630),
 ('this', 35080),
 ('s', 33815),
 ('as', 26308),
 ('with', 23247),
 ('for', 22416),
 ('was', 21917),
 ('film', 20937),
 ('but', 20822),
 ('movie', 19074),
 ('his', 17227),
 ('on', 17008),
 ('you', 16681),
 ('he', 16282),
 ('are', 14807),
 ('not', 14272),
 ('t', 13720),
 ('one', 13655),
 ('have', 12587),
 ('\n', 12500),
 ('be', 12416),
 ('by', 11997),
 ('all', 11942),
 ('who', 11464),
 ('an', 11294),
 ('at', 11234),
 ('from', 10767),
 ('her', 10474),
 ('they', 9895),
 ('has', 9186),
 ('so', 9154),
 ('like', 9038),
 ('about', 8313),
 ('very', 8305),
 ('out', 8134),
 ('there', 8057),
 ('she', 7779),
 ('what', 7737),
 ('or', 7732),
 ('good', 7720),
 ('more', 7521),
 ('when', 7456),
 ('some', 7441),
 ('if', 7285),
 ('just', 7152),
 ('can', 7001),
 ('story', 6780),
 ('time', 6515),
 ('

In [20]:
negative_counts.most_common()

[('', 548962),
 ('.', 167538),
 ('the', 163389),
 ('a', 79321),
 ('and', 74385),
 ('of', 69009),
 ('to', 68974),
 ('br', 52637),
 ('is', 50083),
 ('it', 48327),
 ('i', 46880),
 ('in', 43753),
 ('this', 40920),
 ('that', 37615),
 ('s', 31546),
 ('was', 26291),
 ('movie', 24965),
 ('for', 21927),
 ('but', 21781),
 ('with', 20878),
 ('as', 20625),
 ('t', 20361),
 ('film', 19218),
 ('you', 17549),
 ('on', 17192),
 ('not', 16354),
 ('have', 15144),
 ('are', 14623),
 ('be', 14541),
 ('he', 13856),
 ('one', 13134),
 ('they', 13011),
 ('\n', 12500),
 ('at', 12279),
 ('his', 12147),
 ('all', 12036),
 ('so', 11463),
 ('like', 11238),
 ('there', 10775),
 ('just', 10619),
 ('by', 10549),
 ('or', 10272),
 ('an', 10266),
 ('who', 9969),
 ('from', 9731),
 ('if', 9518),
 ('about', 9061),
 ('out', 8979),
 ('what', 8422),
 ('some', 8306),
 ('no', 8143),
 ('her', 7947),
 ('even', 7687),
 ('can', 7653),
 ('has', 7604),
 ('good', 7423),
 ('bad', 7401),
 ('would', 7036),
 ('up', 6970),
 ('only', 6781),
 ('m

The above is just to show the most common words in the positive and negative sentences. However, there are a lot of unnecessary words like `the`, `a`, `was`, and so on. Can you find a way to show the relevant words and not these words? 

```
Hint: Stop Words removal or normalizing each term.
```

In [21]:
words[:30]
# oneD[:30]

[['bromwell',
  'high',
  'is',
  'a',
  'cartoon',
  'comedy',
  'it',
  'ran',
  'at',
  'the',
  'same',
  'time',
  'as',
  'some',
  'other',
  'programs',
  'about',
  'school',
  'life',
  'such',
  'as',
  'teachers',
  'my',
  'years',
  'in',
  'the',
  'teaching',
  'profession',
  'lead',
  'me',
  'to',
  'believe',
  'that',
  'bromwell',
  'high',
  's',
  'satire',
  'is',
  'much',
  'closer',
  'to',
  'reality',
  'than',
  'is',
  'teachers',
  'the',
  'scramble',
  'to',
  'survive',
  'financially',
  'the',
  'insightful',
  'students',
  'who',
  'can',
  'see',
  'right',
  'through',
  'their',
  'pathetic',
  'teachers',
  'pomp',
  'the',
  'pettiness',
  'of',
  'the',
  'whole',
  'situation',
  'all',
  'remind',
  'me',
  'of',
  'the',
  'schools',
  'i',
  'knew',
  'and',
  'their',
  'students',
  'when',
  'i',
  'saw',
  'the',
  'episode',
  'in',
  'which',
  'a',
  'student',
  'repeatedly',
  'tried',
  'to',
  'burn',
  'down',
  'the',
  'sc

In [22]:
import nltk
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
nltk.download('stopwords')

stop_words = set(stopwords.words('english')) 
words_wo_stopwords = []

for i in range(0, len(words)):
    # Filter stop words and add mapping int -> string
    
    sentence = []
    for word in words[i]:
        
        if not word in stop_words:
            sentence.append(word)
    
    words_wo_stopwords.append(sentence)
    
words = words_wo_stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Matthias\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [23]:
#print(len(vocab_to_int))
for word in words_wo_stopwords[0]:
    print(word)
    
    print(vocab_to_int[word])

bromwell
10001
high
20926
cartoon
32548
comedy
8383
ran
25038
time
155
programs
4697
school
60556
life
19395
teachers
11523
years
11277
teaching
15504
profession
69588
lead
60272
believe
33248
bromwell
10001
high
20926
satire
1946
much
2143
closer
69714
reality
65671
teachers
11523
scramble
7587
survive
38
financially
2203
insightful
858
students
40050
see
39373
right
24483
pathetic
4251
teachers
11523
pomp
28812
pettiness
46849
whole
44388
situation
54778
remind
29038
schools
69406
knew
19358
students
40050
saw
13945
episode
14265
student
69138
repeatedly
51837
tried
12039
burn
12359
school
60556
immediately
270
recalled
60096
high
20926
classic
338
line
33391
inspector
4582
sack
63440
one
795
teachers
11523
student
69138
welcome
6626
bromwell
10001
high
20926
expect
18174
many
56328
adults
13480
age
43969
think
13056
bromwell
10001
high
20926
far
53279
fetched
61344
pity
50790


In [24]:
vocab_to_int['bromwell']

10001

## One hot encoding

We need one hot encoding for the labels. Think of a reason why we need one hot encoded labels for classes?

## Task 3: Create one hot encoding for the labels. 

* Write the one hot encoding logic in the `one_hot` function.
* Use 1 for positive label and 0 for negative label.
* Save all the values in the `encoded_labels` function.

In [25]:
# 1 for positive label and 0 for negative label
def one_hot(labels):
    encoded = []
    for i in range(0, len(labels)):
       # print(labels[i])
        if labels[i] == 'positive\n':
            encoded.append(1)
        else:
            encoded.append(0)
            
    return encoded
    
encoded_labels = one_hot(labels)

In [26]:
#print the length of your labels and uncomment next line only if the encoded_labels size is 25001.
# If you dont get the intuition behind this step, print encoded_labels to see it.
encoded_labels = encoded_labels[:25000]

In [27]:
len(encoded_labels)

25000

In [28]:
# Make an array of arrays holding the integer representation of each word in a review
reviews_ints = []
for review in words:
    reviews_ints.append([vocab_to_int[word] for word in review])
    
print(reviews_ints[1])

[42787, 37036, 72479, 46501, 55643, 16874, 13443, 54419, 61237, 71883, 59285, 8383, 57530, 29993, 29601, 47653, 17248, 11286, 49555, 21417, 67691, 39334, 65418, 540, 59285, 44388, 155, 28585, 26051, 3604, 25253, 7663, 9006, 41644, 47653, 22822, 16187, 21074, 26927, 65638, 61996, 52093, 48666, 13496, 38817, 27149, 71723, 1492, 13056, 7307, 68145, 58152, 10728, 23725, 772, 58152, 49294, 63925, 69083, 72812, 68699, 3015, 23955]


In [29]:
# This step is to see if any review is empty and we remove it. Otherwise the input will be all zeroes.
review_lens = Counter([len(x) for x in reviews_ints])
print("Zero-length reviews: {}".format(review_lens[0]))
print("Maximum review length: {}".format(max(review_lens)))

# There is no empty review...

Zero-length reviews: 0
Maximum review length: 1442


In [30]:
print('Number of reviews before removing outliers: ', len(reviews_ints))

## remove any reviews/labels with zero length from the reviews_ints list.

# get indices of any reviews with length 0
non_zero_idx = [ii for ii, review in enumerate(reviews_ints) if len(review) != 0]

# remove 0-length reviews and their labels
reviews_ints = [reviews_ints[ii] for ii in non_zero_idx]
encoded_labels = np.array([encoded_labels[ii] for ii in non_zero_idx])

print('Number of reviews after removing outliers: ', len(reviews_ints))

Number of reviews before removing outliers:  25000
Number of reviews after removing outliers:  25000


In [31]:
len(encoded_labels)

25000

## Task 4: Padding the data

> Define a function that returns an array `features` that contains the padded data, of a standard size, that we'll pass to the network. 
* The data should come from `review_ints`, since we want to feed integers to the network. 
* Each row should be `seq_length` elements long. 
* For reviews shorter than `seq_length` words, **left pad** with 0s. That is, if the review is `['best', 'movie', 'ever']`, `[117, 18, 128]` as integers, the row will look like `[0, 0, 0, ..., 0, 117, 18, 128]`. 
* For reviews longer than `seq_length`, use only the first `seq_length` words as the feature vector.

As a small example, if the `seq_length=10` and an input review is: 
```
[117, 18, 128]
```
The resultant, padded sequence should be: 

```
[0, 0, 0, 0, 0, 0, 0, 117, 18, 128]
```

**Your final `features` array should be a 2D array, with as many rows as there are reviews, and as many columns as the specified `seq_length`.**

In [49]:
# Write the logic for padding the data
import numpy as np

def pad_features(reviews_ints, seq_length):
    features =[]
    #print(type(reviews_ints))
    #print(type(reviews_ints[0]))
    #print(type(reviews_ints[0][0]))
    
    for sen in reviews_ints:
        numberpad = seq_length-len(sen)
        toFill = [0] * numberpad
        tmpRes = toFill + sen
        #TODO check why some sentences are bigger than 200
        if len(sen) > 200:
            tmpRes = sen[:200]
        features.append(tmpRes)
        

    features = np.array(features)
    print(type(features))
    return features

In [50]:
# Verify if everything till now is correct. 

seq_length = 200

features = pad_features(reviews_ints, seq_length=seq_length)

## test statements - do not change - ##
assert len(features)==len(reviews_ints), "Your features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."


#features = features.reshape(-1, 1)
# print first 10 values of the first 30 batches
print(features[:30,:10])
#print(len(features[2]))

<class 'numpy.ndarray'>
[[    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [49444 22211 47913 60322 19300 42289 11277 13638 37437 56493]
 [55985 16874 32600 27816 44368  5470 34555 43426 46258 62300]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [14669 10389  5371 60523 62597 39373 43643   795 56328 46152]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [32764 55222 41079 66442 45125 29907 57842 52577 72204 70687]
 [    0     0     0     0     0

Now we have everything ready. It's time to split our dataset into `Train`, `Test` and `Validate`. 

Read more about the train-test-split here : https://cs230-stanford.github.io/train-dev-test-split.html

## Task 5: Lets create train, test and val split in the ratio of 8:1:1.  

Hint: Either use shuffle and slicing in Python or use train-test-val split in Sklearn. 

In [51]:
from sklearn.model_selection import train_test_split

train_frac = 0.8
val_frac = 0.1
test_frac = 0.1

def train_test_val_split(features, encoded_labels):
    train_x, test_x, train_y, test_y = train_test_split(features, encoded_labels, test_size=0.2, random_state=1)
    test_x, val_x, test_y, val_y = train_test_split(test_x, test_y, test_size=0.5, random_state=1)
    #return array(train_x), array(val_x), array(test_x), array(train_y), array(val_y), array(test_y)
    return train_x, val_x, test_x, train_y, val_y, test_y

#def train_test_val_split(features):
    #X_train, X_test, y_train, y_test = train_test_split(features, test_size=0.2, random_state=42)


#def train_test_val_labels(encoded_labels):
    #return np.split(encoded_labels.sample(frac=1), [int(train_frac*len(encoded_labels)), int(1-val_frac*len(encoded_labels))]) 

train_x, val_x, test_x, train_y, val_y, test_y = train_test_val_split(features, encoded_labels)

In [52]:
## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(20000, 200) 
Validation set: 	(2500, 200) 
Test set: 		(2500, 200)


## DataLoaders and Batching

After creating training, test, and validation data, we can create DataLoaders for this data by following two steps:
1. Create a known format for accessing our data, using [TensorDataset](https://pytorch.org/docs/stable/data.html#) which takes in an input set of data and a target set of data with the same first dimension, and creates a dataset.
2. Create DataLoaders and batch our training, validation, and test Tensor datasets.

```
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
train_loader = DataLoader(train_data, batch_size=batch_size)
```

This is an alternative to creating a generator function for batching our data into full batches.

### Task 6: Create a generator function for the dataset. 
See the above link for more info.

In [79]:
import torch
from torch.utils.data import TensorDataset, DataLoader

#train_x_tensor = torch.stack([torch.Tensor(i) for i in train_x])
#train_y_tensor = torch.stack([torch.Tensor(i) for i in train_y])
#test_x_tensor = torch.stack([torch.Tensor(i) for i in test_x])
#test_y_tensor = torch.stack([torch.Tensor(i) for i in test_y])
#val_x_tensor = torch.stack([torch.Tensor(i) for i in val_x])
#val_y_tensor = torch.stack([torch.Tensor(i) for i in val_y])

#for f in train_y:
#    print("--------")
#    print(f)
#    print(type(array(f)))
#    print(type(train_x))
#    break;

# create Tensor datasets for train, test and val
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))
#TensorDataset(train_x_tensor, train_y_tensor)
#valid_data = TensorDataset(val_x_tensor, val_y_tensor)
#test_data = TensorDataset(test_x_tensor, test_y_tensor)

# dataloaders
batch_size = 50 

# make sure to SHUFFLE your training data. Keep Shuffle=True.
train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True)
valid_loader = DataLoader(valid_data, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_data, batch_size=batch_size, shuffle=True)

In [80]:
# obtain one batch of training data and label. 
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([50, 200])
Sample input: 
 tensor([[     0,      0,      0,  ...,  66278,  46279,  58688],
        [ 53135,  67086,  57686,  ...,  10628,  29466,  18952],
        [  6440,  45418,    795,  ...,   4593,  72330,  11538],
        ...,
        [     0,      0,      0,  ...,  19351,  15407,  30540],
        [     0,      0,      0,  ...,  55054,    795,  23299],
        [     0,      0,      0,  ...,  56938,  37146,  50826]], dtype=torch.int32)

Sample label size:  torch.Size([50])
Sample label: 
 tensor([ 0,  1,  1,  0,  0,  0,  0,  1,  1,  1,  1,  1,  0,  0,
         0,  0,  1,  0,  0,  0,  0,  0,  1,  1,  1,  0,  0,  0,
         0,  0,  0,  1,  0,  1,  1,  0,  1,  0,  0,  1,  1,  1,
         1,  1,  1,  0,  1,  1,  1,  0], dtype=torch.int32)


In [81]:
# Check if GPU is available.
train_on_gpu=torch.cuda.is_available()

if(train_on_gpu):
    print('Training on GPU.')
else:
    print('No GPU available, training on CPU.')

Training on GPU.


## Creating the Model 

Here we are creating a simple RNN in PyTorch and pass the output to the a Linear layer and Sigmoid at the end to get the probability score and prediction as POSITIVE or NEGATIVE. 

The network is very similar to the CNN network created in Exercise 2. 

More info available at: https://pytorch.org/docs/0.3.1/nn.html?highlight=rnn#torch.nn.RNN

Read about the parameters that the RNN takes and see what will happen when `batch_first` is set as `True`.

In [82]:
import torch.nn as nn

class SentimentRNN(nn.Module):
    """
    The RNN model that will be used to perform Sentiment analysis.
    """

    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        """
        Initialize the model by setting up the layers.
        """
        super(SentimentRNN, self).__init__()

        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        
        
        # RNN layer
        self.rnn = nn.RNN(vocab_size, hidden_dim, n_layers, dropout=drop_prob, batch_first=True)
        
        # embedding and RNN layers
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        
        
        # dropout layer
        self.dropout = nn.Dropout(0.3)
        
        # linear and sigmoid layers
        self.fc = nn.Linear(hidden_dim, output_size)
        self.sig = nn.Sigmoid()
        

    def forward(self, x, hidden):
        """
        Perform a forward pass of our model on some input and hidden state.
        """
        batch_size = x.size(0)
        x = x.long()
        
        # RNN out layer
        embeds = self.embedding(x)
        rnn_out, hidden = self.rnn(x, hidden)
    
        # stack up lstm outputs
        rnn_out = rnn_out.view(-1, self.hidden_dim)
        
        # dropout and fully-connected layer
        out = self.dropout(rnn_out)
        out = self.fc(out)
        # sigmoid function
        sig_out = self.sig(out)
        
        # reshape to be batch_size first
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1] # get last batch of labels
        
        # return last sigmoid output and hidden state
        return sig_out, hidden
   
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x hidden_dim,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())
        
        return hidden


## Task 7 : Know the shape

Given a batch of 64 and input size as 1 and a sequence length of 200 to a RNN with 2 stacked layers and 512 hidden layers, find the shape of input data (x) and the hidden dimension (hidden) specified in the forward pass of the network. Note, the batch_first is kept to be True. 



In [83]:
# Instantiate the model w/ hyperparams
vocab_size = len(vocab_to_int)+1 # +1 for the 0 padding + our word tokens
output_size = 1
hidden_dim = 512
embedding_dim = 300
n_layers = 2

net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)

print(net)

SentimentRNN(
  (rnn): RNN(74073, 512, num_layers=2, batch_first=True, dropout=0.5)
  (embedding): Embedding(74073, 300)
  (dropout): Dropout(p=0.3)
  (fc): Linear(in_features=512, out_features=1, bias=True)
  (sig): Sigmoid()
)



## Task 8: LSTM 

Before we start creating the LSTM, it is important to understand LSTM and to know why we prefer LSTM over a Vanilla RNN for this task. 
> Here are some good links to know about LSTM:
* [Colah Blog](http://colah.github.io/posts/2015-08-Understanding-LSTMs/)
* [Understanding LSTM](http://blog.echen.me/2017/05/30/exploring-lstms/)
* [RNN effectiveness](http://karpathy.github.io/2015/05/21/rnn-effectiveness/)


Now create a class named SentimentLSTM with `n_layers=2`, and rest all hyperparameters same as before. Also, create an embedding layer and feed the output of the embedding layer as input to the LSTM model. Dont forget to add a regularizer (dropout) layer after the LSTM layer with p=0.4 to prevent overfitting. 

In [84]:
import torch.nn as nn

class SentimentLSTM(nn.Module):
    """
    The RNN model that will be used to perform Sentiment analysis.
    """

    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        """
        Initialize the model by setting up the layers.
        """
        super(SentimentLSTM, self).__init__()

        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        
        # embedding and LSTM layers
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers, dropout=drop_prob, batch_first=True)
        
        # dropout layer
        self.dropout = nn.Dropout(0.4)
        
        # linear and sigmoid layer
        self.fc = nn.Linear(hidden_dim, output_size)
        self.sig = nn.Sigmoid()
                

    def forward(self, x, hidden):
        """
        Perform a forward pass of our model on some input and hidden state.
        """
        batch_size = x.size(0)
        x = x.long()
        
        # embeddings and lstm_out
        embeds = self.embedding(x)
        lstm_out, hidden = self.lstm(embeds, hidden)
        
        # stack up lstm outputs
        lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)
        
        # dropout and fully connected layer
        out = self.dropout(lstm_out)
        out = self.fc(out)
        
        # sigmoid function
        sig_out = self.sig(out)
        
        # reshape to be batch_size first
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1] # get last batch of labels
        
        # return last sigmoid output and hidden state
        return sig_out, hidden
    
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x hidden_dim,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        if(train_on_gpu):
          hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                   weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
          hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                   weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())
        
        return hidden
    
        

## Instantiate the network

Here, we'll instantiate the network. First up, defining the hyperparameters.

* `vocab_size`: Size of our vocabulary or the range of values for our input, word tokens.
* `output_size`: Size of our desired output; the number of class scores we want to output (pos/neg).
* `embedding_dim`: Number of columns in the embedding lookup table; size of our embeddings.
* `hidden_dim`: Number of units in the hidden layers of our LSTM cells. Usually larger is better performance wise. Common values are 128, 256, 512, etc.
* `n_layers`: Number of LSTM layers in the network. Typically between 1-3

In [85]:
# Instantiate the model with these hyperparameters
vocab_size = len(vocab_to_int)+1 # +1 for the 0 padding + our word tokens
output_size = 1
embedding_dim = 300
hidden_dim = 256
n_layers = 2

net = SentimentLSTM(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)

print(net)

SentimentLSTM(
  (embedding): Embedding(74073, 300)
  (lstm): LSTM(300, 256, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.4)
  (fc): Linear(in_features=256, out_features=1, bias=True)
  (sig): Sigmoid()
)


In [86]:
import torch
# loss and optimization functions
lr=0.001

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=lr)


### Task 9: Loss Functions
We are using `BCELoss (Binary Cross Entropy Loss)` since we have two output classes. 

Can Cross Entropy Loss be used instead of BCELoss? 

If no, why not? If yes, how?

Is `NLLLoss()` and last layer as `LogSoftmax()` is same as using `CrossEntropyLoss()` with a Softmax final layer? Can you get the mathematical intuition behind it?

In [87]:
# training params

epochs = 4 # 3-4 is approx where I noticed the validation loss stop decreasing

counter = 0
print_every = 100
clip=5 # gradient clipping

# move model to GPU, if available
if(train_on_gpu):
    net.cuda()

net.train()
# train for some number of epochs
for e in range(epochs):
    # initialize hidden state
    h = net.init_hidden(batch_size)

    # batch loop
    for inputs, labels in train_loader:
        counter += 1

        if(train_on_gpu):
            inputs, labels = inputs.cuda(), labels.cuda()

        # Creating new variables for the hidden state, otherwise
        # we'd backprop through the entire training history
        h = tuple([each.data for each in h])

        # zero accumulated gradients
        net.zero_grad()

        # get the output from the model
        output, h = net(inputs, h)

        # calculate the loss and perform backprop
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()
        # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()

        # loss stats
        if counter % print_every == 0:
            # Get validation loss
            val_h = net.init_hidden(batch_size)
            val_losses = []
            net.eval()
            for inputs, labels in valid_loader:

                # Creating new variables for the hidden state, otherwise
                # we'd backprop through the entire training history
                val_h = tuple([each.data for each in val_h])

                if(train_on_gpu):
                    inputs, labels = inputs.cuda(), labels.cuda()

                output, val_h = net(inputs, val_h)
                val_loss = criterion(output.squeeze(), labels.float())

                val_losses.append(val_loss.item())

            net.train()
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

#save model
torch.save(net, 'trained_model.pt')

Epoch: 1/4... Step: 100... Loss: 0.508462... Val Loss: 0.597949
Epoch: 1/4... Step: 200... Loss: 0.546738... Val Loss: 0.573575
Epoch: 1/4... Step: 300... Loss: 0.463303... Val Loss: 0.511403
Epoch: 1/4... Step: 400... Loss: 0.392615... Val Loss: 0.486103
Epoch: 2/4... Step: 500... Loss: 0.341293... Val Loss: 0.502958
Epoch: 2/4... Step: 600... Loss: 0.356802... Val Loss: 0.446318
Epoch: 2/4... Step: 700... Loss: 0.323652... Val Loss: 0.413317
Epoch: 2/4... Step: 800... Loss: 0.326981... Val Loss: 0.425349
Epoch: 3/4... Step: 900... Loss: 0.312010... Val Loss: 0.406346
Epoch: 3/4... Step: 1000... Loss: 0.388595... Val Loss: 0.400288
Epoch: 3/4... Step: 1100... Loss: 0.247629... Val Loss: 0.382353
Epoch: 3/4... Step: 1200... Loss: 0.408125... Val Loss: 0.397322
Epoch: 4/4... Step: 1300... Loss: 0.099749... Val Loss: 0.444721
Epoch: 4/4... Step: 1400... Loss: 0.076807... Val Loss: 0.423335
Epoch: 4/4... Step: 1500... Loss: 0.092872... Val Loss: 0.412531
Epoch: 4/4... Step: 1600... Loss: 

c:\program files\python35\lib\site-packages\torch\serialization.py:193: UserWarning: Couldn't retrieve source code for container of type SentimentLSTM. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "


## Inference
Once we are done with training and validating, we can improve training loss and validation loss by playing around with the hyperparameters. Can you find a better set of hyperparams? Play around with it. 

### Task 10: Prediction Function
Now write a prediction function to predict the output for the test set created. Save the results in a CSV file with one column as the reviews and the prediction in the next column. Calculate the accuracy of the test set.

In [88]:
#load model
model = torch.load('trained_model.pt')

def predict():
    model.eval()
    test_output = model(test_x)
    arr = test_output.data.cpu().numpy()
    np.savetxt('output.csv', arr)

## Bonus Question: Create an app using Flask

> Extra bonus points if someone attempts this question:
* Save the trained model checkpoints.
* Create a Flask app and load the model. A similar work in the field of CNN has been done here : https://github.com/kumar-shridhar/Business-Card-Detector (Check `app.py`)
* You can use hosting services like Heroku and/or with Docker to host your app and show it to everyone. 
Example here: https://github.com/selimrbd/sentiment_analysis/blob/master/Dockerfile
